### ISSUE TITLE
Title for Lunch and Learn 2019

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-geoforall-lab/open-science-course#10]
1. Single Person Workflows in Git
2. Managing Your Files with Git

**Comment by wenzeslaus** [comment]
3. Git for Personal Use

**Comment by ncinglis** [comment]
4. Basic Workflows for Managing Projects with Git

**Comment by wenzeslaus** [comment]
> Basic Workflows for Managing Projects with Git

 I like that.

...Managing Personal Projects...? Or is the "personal" too free time related as opposed to research work? Well, maybe that can be part of the description.

**Comment by ncinglis** [comment]
> > Basic Workflows for Managing Projects with Git
> 
> I like that.
> 
> ...Managing Personal Projects...? Or is the "personal" too free time related as opposed to research work? Well, maybe that can be part of the description.

I think "personal" sounds to much like non-work related. We can be more specific that it's not for collaborative projects (yet) in the description.  Does that work for you?

**Comment by wenzeslaus** [comment]
> Basic Workflows for Managing Projects with Git

Agreed. Let's go with that.
