### ISSUE TITLE
Discuss CoCalc, Google Colab, RStudio Cloud

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-geoforall-lab/open-science-course#27]
Discuss how CoCalc, Google Colab, RStudio Cloud are or are not useful for open science publishing (versus cloud workstation/computing).

**Comment by petrasovaa** [comment]
Possibly list Google colab here:
https://ncsu-geoforall-lab.github.io/open-science-course/lectures/python-in-binder.html#/3

**Comment by petrasovaa** [comment]
Maybe mention hydroshare?

**Comment by wenzeslaus** [comment]
Done. Colab is discussed few slides later, now on a separate Binder Alternatives slide. HydroShare added too (was already in data repositories).
